server:
  port: 8668

spring:
  jackson:
    serialization:
      indent-output: true

logging:
  level:
    root: INFO
    com.czy.qwen: DEBUG
    com.czy.qwen.server.QwenAiServiceImpl: INFO

dashscope:
  api-key: sk-33b96ae17cba4c928a8bf7bcab5b5b08

ai:
  session:
    timeout-seconds: 1800 # 单位：s
    cleanup-interval-ms: 10000 # 单位：ms