<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ai-practice</artifactId>
        <groupId>com.czy.ai</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ai-practice-langchain4j</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>ai-practice-langchain4j-common</module>
        <module>ai-practice-langchain4j-starter</module>
        <module>ai-practice-langchain4j-service</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.czy.ai</groupId>
                <artifactId>ai-practice-langchain4j-common</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.czy.ai</groupId>
                <artifactId>ai-practice-langchain4j-service</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- LangChain4j 依赖版本 -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>

            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-open-ai</artifactId>
                <version>${langchain4j.version}</version>
            </dependency>


        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
